#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SlotsGame.Resource", IsApplication=true)]

namespace SlotsGame
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int img1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int img2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int img3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int img4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int img5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int img6 = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int btnStart = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int message = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int slot1 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int slot2 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int slot3 = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int slots = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int status = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int txtCash = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int wbPostContent = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LayoutSecond = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int btn_start_title = 2130968578;
			
			// aapt resource value: 0x7f040012
			public const int disable_back_button = 2130968594;
			
			// aapt resource value: 0x7f040001
			public const int message_text = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int msg_cash = 2130968582;
			
			// aapt resource value: 0x7f04000f
			public const int msg_error = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int msg_exit = 2130968590;
			
			// aapt resource value: 0x7f040005
			public const int msg_gameover = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int msg_lose = 2130968580;
			
			// aapt resource value: 0x7f040010
			public const int msg_no_network = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int msg_try_again = 2130968589;
			
			// aapt resource value: 0x7f040013
			public const int msg_wait_loading = 2130968595;
			
			// aapt resource value: 0x7f040007
			public const int msg_welcome = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int msg_win = 2130968579;
			
			// aapt resource value: 0x7f040011
			public const int remote_checkout_interval = 2130968593;
			
			// aapt resource value: 0x7f040009
			public const int roll1 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int roll2 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int roll3 = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int start_cash = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int url_ads_manager = 2130968588;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
